import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="w-[1920px] min-w-[1920px] max-w-[1920px] h-[1080px] p-[10px] m-auto box-border relative">
        {children}
      </body>
    </html>
  );
}
